FROM openjdk:8u191-jre-alpine3.8

RUN apk add curl jq
#Workspaces
WORKDIR /usr/share/udemy

#Add jars

ADD target/selenium-docker.jar        selenium-docker.jar
ADD target/selenium-docker-tests.jar  selenium-docker-tests.jar
ADD target/libs                       libs

ADD book-flight-module.xml            book-flight-module.xml
ADD search-module.xml                 search-module.xml
Add healthcheck.sh                    healthcheck.sh

#ENTRYPOINT sh healthcheck.sh
ENTRYPOINT sleep 3 && java -cp selenium-docker.jar:selenium-docker-tests.jar:libs/* \
           -DHUB_HOST=$HUB_HOST
           -DBROWSER=$BROWSER \
           org.testng.TestNG $MODULE